--[VIII] SEQUENCE : 순차번호 생성기, 대부분 인위적인 PK 사용 용도 
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 9999
    MINVALUE 1
    NOCACHE 
    NOCYCLE;
SELECT FRIEND_SEQ.NEXTVAL FROM DUAL;    
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    MAXVALUE 9999
    NOCACHE
    NOCYCLE;
DROP TABLE FRIEND;    
CREATE TABLE FRIEND(
    NUM     NUMBER(4) PRIMARY KEY, --시퀀스 이용
    NAME    VARCHAR2(30) NOT NULL,
    TEL        VARCHAR2(30) UNIQUE,  --NULL 허용, 유일한 값
    ADDRESS VARCHAR2(200), 
    LAST_MODIFYED DATE DEFAULT SYSDATE
);
INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS) 
    VALUES(FRIEND_SEQ.NEXTVAL ,'홍길동' ,NULL ,'서울시 강남구');
INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS) 
    VALUES(FRIEND_SEQ.NEXTVAL ,'박길동' ,'010-9999-9999' ,'서울시 강남구 강남대로94길 13 삼겸빌딩 402');
SELECT * FROM FRIEND;     
INSERT INTO FRIEND (NUM,NAME,TEL,ADDRESS)
    VALUES(FRIEND_SEQ.NEXTVAL, '신길동','010-8888-8888','서울시 영등포구');
    SELECT * FROM FRIEND;     
SELECT FRIEND_SEQ.CURRVAL FROM DUAL; -- 현재 시퀀스 값
COMMIT;
-- EX 초기값 101부터 최대값 999,999까지 1씩 증가하는 test_seq 시퀀스를 생성
CREATE SEQUENCE TEST_SEQ START WITH 101 MAXVALUE 999999 NOCACHE NOCYCLE;
SELECT TEST_SEQ.CURRVAL FROM DUAL; --시퀀스의 현재 값이 없어서 에러 
SELECT TEST_SEQ.NEXTVAL FROM DUAL;

--연습문제 1 (시험대비)
DROP SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_SEQ
    MAXVALUE 9999
    NOCACHE 
    NOCYCLE;
DROP SEQUENCE MEMBER_LEVEL_SEQ;
CREATE SEQUENCE MEMBER_LEVEL_SEQ
    MINVALUE -1
    MAXVALUE 9999
    NOCACHE
    NOCYCLE;
CREATE TABLE MEMBER_LEVEL(
    LEVELNO NUMBER(2) PRIMARY KEY,
    LEVELNAME VARCHAR2(20) NOT NULL);
CREATE TABLE MEMBER(
    mNO NUMBER(4) PRIMARY KEY,
    mNAME VARCHAR2(20) NOT NULL,
    mPW VARCHAR2(20) CHECK(LENGTH(mPW)<=8),
    mEMAIL VARCHAR2(30) UNIQUE,
    mPOINT NUMBER(8)  CHECK(mPOINT >=0),
    mRDATE DATE DEFAULT SYSDATE,
    LEVELNO NUMBER(2) REFERENCES MEMBER_LEVEL(LEVELNO));    
    
INSERT INTO MEMBER_LEVEL VALUES(MEMBER_LEVEL_SEQ.NEXTVAL, 'black');
INSERT INTO MEMBER_LEVEL VALUES(MEMBER_LEVEL_SEQ.NEXTVAL, '일반');
INSERT INTO MEMBER_LEVEL VALUES(MEMBER_LEVEL_SEQ.NEXTVAL, '실버');
INSERT INTO MEMBER_LEVEL VALUES(MEMBER_LEVEL_SEQ.NEXTVAL, '골드');
SELECT *FROM MEMBER_LEVEL;
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL,'홍길동','aa','hong@hong.com',0,'22/03/10',0);
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL,'신길동','bb','sing@sin.com',1000,'22/04/01',1);
SELECT * FROM MEMBER;

SELECT mNO,mNAME,TO_CHAR(mRDATE,'YYYY-MM-DD'),mEMAIL,mPOINT point, LEVELNAME || '고객' LEVELNAME
    FROM MEMBER M, MEMBER_LEVEL L
    WHERE M.LEVELNO = L.LEVELNO; 
    