DROP TABLE CUS_LEVEL;
CREATE TABLE CUS_LEVEL(
    LEVELNO NUMBER(2) PRIMARY KEY,
    LEVELNAME VARCHAR2(20) NOT NULL);

DROP TABLE CUSTOMER;
CREATE TABLE CUSTOMER(
    CNO NUMBER(2) PRIMARY KEY,
    CNAME VARCHAR2(30) NOT NULL,
    JOINDATE DATE DEFAULT SYSDATE,
    PHONE VARCHAR2(30) UNIQUE,
    POINT VARCHAR2(20),
    LEVELNO NUMBER(2) REFERENCES CUS_LEVEL(LEVELNO));    
DROP SEQUENCE CUS_SQ;
CREATE SEQUENCE CUS_SQ
    MAXVALUE 99
    NOCACHE
    NOCYCLE;
INSERT INTO CUS_LEVEL VALUES(1,'VVIP');
INSERT INTO CUS_LEVEL VALUES(2,'VIP');
INSERT INTO CUS_LEVEL VALUES(3,'NORMAL');
INSERT INTO CUS_LEVEL VALUES(4,'BLACK');
INSERT INTO CUSTOMER VALUES(CUS_SQ.NEXTVAL,'È«±æµ¿','22/03/10','010-9999-9999',0,1);
INSERT INTO CUSTOMER VALUES(CUS_SQ.NEXTVAL,'ÀÌÃ¶¼ö','22/04/19','010-8888-8888',NULL,2);
SELECT CNO, CNAME, TO_CHAR(JOINDATE,'RRRR-MM-DD') JOINDATE, PHONE, NVL(POINT,'NULL') POINT , LEVELNAME
FROM CUSTOMER C, CUS_LEVEL L 
WHERE C.LEVELNO = L.LEVELNO; 
