DROP TABLE CUSTOMER;
CREATE TABLE CUSTOMER(
    CNO   NUMBER(2) PRIMARY KEY,
    PHONE VARCHAR2(20) UNIQUE,
    NAME VARCHAR2(20) NOT NULL,
    POINT NUMBER(9,0) DEFAULT 1000);
    
DROP  SEQUENCE CUS_SEQ;
CREATE SEQUENCE CUS_SEQ MAXVALUE 9999 NOCACHE NOCYCLE;  

INSERT INTO CUSTOMER  VALUES(CUS_SEQ.NEXTVAL,'010-9999-9999','김토치',20000);
INSERT INTO CUSTOMER  VALUES(CUS_SEQ.NEXTVAL,'010-8888-8888', '김토토', 5000);
INSERT INTO CUSTOMER  VALUES(CUS_SEQ.NEXTVAL,'010-7777-7777', '김루키' ,1000000);    
COMMIT;
SELECT * FROM CUSTOMER;

 

--요구사항 
--가입 PUBLIC INT INSERT
INSERT INTO CUSTOMER (CNO,PHONE,NAME) VALUES(CUS_SEQ.NEXTVAL, '010-5555-5555','김민우');
--폰 조회    
--public ArrayList<CustomerDto> phoneCustomer(String phone)
SELECT * FROM CUSTOMER WHERE PHONE LIKE '%'||'9999' ;
--출력 
--public ArrayList<CustomerDto> getCustomers()
SELECT * FROM CUSTOMER;
COMMIT;