DROP TABLE FRIEND;
DROP SEQUENCE FRIEND_SEQ;
CREATE TABLE FRIEND(
    N    NUMBER(3) PRIMARY KEY,
    FNAME VARCHAR2(30) ,
    TEL VARCHAR2(30)
);
CREATE SEQUENCE FRIEND_SEQ
 START WITH 1
    INCREMENT BY 1
    MAXVALUE 9999
    MINVALUE 1
    NOCACHE 
    NOCYCLE;

-- 1. SELECT ALL
SELECT * FROM FRIEND;

--2 INSERT
INSERT INTO FRIEND(N, FNAME,TEL) VALUES(FRIEND_SEQ.NEXTVAL,'홍길동','010-9999-9999');
INSERT INTO FRIEND(N, FNAME,TEL) VALUES(FRIEND_SEQ.NEXTVAL,'신길동','010-1234-5678');
INSERT INTO FRIEND(N, FNAME,TEL) VALUES(FRIEND_SEQ.NEXTVAL,'김길동','010-8888-8888');
--3 친구 검색
SELECT * FROM FRIEND WHERE NAME LIKE '%'||'길'||'%' AND TEL LIKE '%9999%';
COMMIT;